### ISSUE TITLE
ㄴㄴ 주석컨밴션여깄음

### ISSUE THREAD

**Issue by clucle** [casicos/Loading-Resources-For-Unity#2]
https://docs.microsoft.com/ko-kr/dotnet/csharp/programming-guide/inside-a-program/coding-conventions#commenting-conventions

이거좀봐바

**Comment by casicos** [comment]
https://docs.microsoft.com/ko-kr/dotnet/csharp/programming-guide/xmldoc/xml-documentation-comments
